Show package version in app
CDCgov/cfa-ring-vax-widget pull request #59
Opened 2024-12-26 18:32 UTC by swo

This way it's clear to use which version is deployed

![image](https://github.com/user-attachments/assets/6e6ff2fd-8e6d-4c08-8756-9c446430dcb7)

2025-01-08 14:44 UTC, afmagee42 commented
I feel like doing this makes us morally obligated to have an actual scheme for updating the version, which is the actual hard part.

2025-01-08 14:45 UTC, afmagee42 requested changes
Without a decision on when to update the version, this strikes me as at-best unhelpful and at worst misleading.

2025-01-08 15:58 UTC, swo commented
I guess there are a few options here:

1. Don't have something like this; maintain status quo
2. Start doing semantic versioning -- I don't think this is crazy. Every push to `prod` should probably involve a version increment anyway. There might even be some way to have a GH Action that checks that this is true.
3. Display some more granular "version" in the app.
   - This could be commit ID. The app has some way to check if it's in a GH repo, call `git log`, figure out the commit, display that (or show nothing, if not in a repo). This wouldn't work if this were a package that got distributed around, but it would work fine for our use case (deployment inside CDC intranet), which is enough for now.
   - Or maybe poetry hash? `poetry.lock` has `metadata` and then `content-hash`, which I'm fairly sure is a hash of the code. If the lockfile is guaranteed to be somewhere when you install a package, then the app could go look for that and read it out. I think this would require some pre-commit checks, to be sure that the lockfile was updated, e.g., on pushes to `prod`.

2025-01-10 16:08 UTC, swo commented
After some synch conversation, we decided that the latest git commit is good enough:
![image](https://github.com/user-attachments/assets/2158787c-3fae-4460-806f-8b9c25d271b5)

2025-01-10 16:35 UTC, afmagee42 approved these changes

2025-01-10 17:06 UTC, merged